DevOCL/src/objects/Active_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the active Ruleset Class Name. Updated automatically when a ruleset is activated or deactivated</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Active Rule</label>
</CustomObject>

DevOCL/src/objects/RuleSet__c.object
<CustomObject>
    <description>RuleSet Catalog and Rule object are in a 1 to many relationship. Contains Version, Rule Definition (JSON) and Activity Status</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catalog_ID__c</fullName>
        <label>Catalog ID</label>
        <referenceTo>RuleSet_Catalog__c</referenceTo>
        <relationshipLabel>RuleSet</relationshipLabel>
        <relationshipName>RuleSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleSet_Name__c</fullName>
        <label>RuleSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compiled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compile Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RuleSet</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>RuleSet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/objects/RuleSet_Catalog__c.object
<CustomObject>
    <description>RuleSet Catalog defines basic information about each rule, including e.g. Name, Effective Start Date, Effective End Date, and Active Version</description>
    <fields>
        <fullName>Active_Class__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Active Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active_Version__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Active Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RuleSet Catalog</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Catalog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/TestActivateRuleSetController_V2.cls
@isTest
public class TestActivateRuleSetController_V2 {
    
    public static testmethod Ruleset_Catalog__c setCatalogData(){
        Ruleset_Catalog__c catalog = new RuleSet_Catalog__c();
        catalog.Name__c = 'Test Catalog';
        catalog.Active_Class__c = 'TestClass';
        catalog.Active_Version__c = 'V-001';
        return catalog;
    }
    
    public static testmethod Ruleset__c setRulesetData(){
        Ruleset__c ruleset = new Ruleset__c();
        ruleset.RuleSet_Name__c = 'Not Available';
        ruleset.Class_Name__c = 'Not Available';
        ruleset.Status__c = 'Compiled';
        ruleset.Active__c = true;
        return ruleset;
    }
    
    public static testmethod Active_Rule__c setCustomSetting(){
        Active_Rule__c myrule = new Active_Rule__c();
        myrule.Name = 'Not Available';
        myrule.Class_Name__c = 'Not Available';
        return myrule;
    }
    
    public static testmethod void testActivateRuleNullsetting(){
        PageReference ref = Page.ActivateRule_V2;
        Test.setCurrentPage(ref);
        ActivateRuleSetController_V2 rcontroller = new ActivateRuleSetController_V2();
        ref = rcontroller.redirectActivatePage();
        Ruleset_Catalog__c catalog = setCatalogData();
        insert catalog;
        Ruleset__c ruleset = setRulesetData();
        ruleset.Catalog_ID__c = Catalog.id;
        insert ruleset;
        ApexPages.currentPage().getParameters().put('id', ruleset.Id);
        ApexPages.currentPage().getParameters().put('Catalogid', catalog.Id);
        ref= rcontroller.redirectActivatePage();
        ref = rcontroller.navigateToHome();
        ref = rcontroller.activateRuleSet(); // Check activating rule - Null custom setting
    }
    
    public static testmethod void testActivateRuleValidsetting(){
        PageReference ref = Page.ActivateRule_V2;
        Test.setCurrentPage(ref);
        ActivateRuleSetController_V2 rcontroller = new ActivateRuleSetController_V2();
        ref = rcontroller.redirectActivatePage();
        Ruleset_Catalog__c catalog = setCatalogData();
        insert catalog;
        Ruleset__c ruleset = setRulesetData();
        ruleset.Catalog_ID__c = Catalog.id;
        insert ruleset;
        Active_Rule__c myrule = setCustomSetting();
        myrule.Name = catalog.Name__c;
        insert myrule;
        ApexPages.currentPage().getParameters().put('id', ruleset.Id);
        ApexPages.currentPage().getParameters().put('Catalogid', catalog.Id);
        ref= rcontroller.redirectActivatePage();
        ref = rcontroller.activateRuleSet(); // Check activating rule - Null custom setting
    }
    
    public static testmethod void testDeActivateRule(){
        PageReference ref = Page.ActivateRule_V2;
        Test.setCurrentPage(ref);
        ActivateRuleSetController_V2 rcontroller = new ActivateRuleSetController_V2();
        ref = rcontroller.redirectActivatePage();
        Ruleset_Catalog__c catalog = setCatalogData();
        insert catalog;
        Ruleset__c ruleset = setRulesetData();
        ruleset.Catalog_ID__c = Catalog.id;
        ruleset.Active__c = False;
        ruleset.Status__c = 'Compiled';
        insert ruleset;
        Active_Rule__c myrule = setCustomSetting();
        myrule.Name = catalog.Name__c;
        insert myrule;
        ApexPages.currentPage().getParameters().put('id', ruleset.Id);
        ApexPages.currentPage().getParameters().put('Catalogid', catalog.Id);
        ref= rcontroller.redirectActivatePage();
        ref = rcontroller.activateRuleSet(); 
    }
    
    public static testmethod void testActivateRuleExistActive(){
        PageReference ref = Page.ActivateRule_V2;
        Test.setCurrentPage(ref);
        ActivateRuleSetController_V2 rcontroller = new ActivateRuleSetController_V2();
        ref = rcontroller.redirectActivatePage();
        Ruleset_Catalog__c catalog = setCatalogData();
        insert catalog;
        Ruleset__c ruleset = setRulesetData();
        ruleset.Catalog_ID__c = Catalog.id;
        ruleset.Active__c = False;
        ruleset.Status__c = 'Compiled';
        insert ruleset;
        Ruleset__c newruleset = setRulesetData();
        newruleset.Active__c = True;
        newruleset.Status__c = 'Compiled';
        newruleset.Catalog_ID__c = Catalog.id;
        insert newruleset;
        rcontroller.ruleset = ruleset;
        Active_Rule__c myrule = setCustomSetting();
        myrule.Name = catalog.Name__c;
        myrule.Class_Name__c = 'Some Class';
        insert myrule;
        ApexPages.currentPage().getParameters().put('id', ruleset.Id);
        ApexPages.currentPage().getParameters().put('Catalogid', catalog.Id);
        ref= rcontroller.redirectActivatePage();
        ref = rcontroller.activateRuleSet(); 
    }

}