DevOCL/src/objects/Active_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the active Ruleset Class Name. Updated automatically when a ruleset is activated or deactivated</description>
    <label>Active Rule</label>
</CustomObject>

DevOCL/src/objects/RuleSet__c.object
<CustomObject>
    <description>RuleSet Catalog and Rule object are in a 1 to many relationship. Contains Version, Rule Definition (JSON) and Activity Status</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catalog_ID__c</fullName>
        <label>Catalog ID</label>
        <referenceTo>RuleSet_Catalog__c</referenceTo>
        <relationshipLabel>RuleSet</relationshipLabel>
        <relationshipName>RuleSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>RuleSet_Name__c</fullName>
        <label>RuleSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RuleSet</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>RuleSet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/objects/RuleSet_Catalog__c.object
<CustomObject>
    <description>RuleSet Catalog defines basic information about each rule, including e.g. Name, Effective Start Date, Effective End Date, and Active Version</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RuleSet Catalog</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Catalog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/TestRulesCatalogController_V2.cls
@isTest
public class TestRulesCatalogController_V2 {
    public static  testmethod void TestRulesCatalogController (){
        RuleSet_Catalog__c Catalog = new RuleSet_Catalog__c();
        Catalog.Name__c = 'Test Catalog 1';
        insert Catalog;
        PageReference ref = Page.RulesCatalogPage_V2;
        Test.setCurrentPage(ref);
        RulesCatalogController_V2 rcontroller = new RulesCatalogController_V2();
        
        Catalog = new RuleSet_Catalog__c();
        Catalog.Name__c = 'Test Catalog 2';
        rcontroller.Catalog = Catalog;
        ref = rcontroller.saveNewCatalog();
        
        Catalog = new RuleSet_Catalog__c();
        Catalog.Name__c = 'Test Catalog 3';
        insert Catalog;
        Active_Rule__c myrule = new Active_Rule__c();
        myrule.Name = Catalog.Name__c;
        insert myrule;
        rcontroller.catalogidToDel = Catalog.Id;
        ref = rcontroller.deleteCatalog();
        
        Catalog = new RuleSet_Catalog__c();
        Catalog.Name__c = 'Test Catalog 4';
        insert Catalog;
        myrule = new Active_Rule__c();
        myrule.Name = Catalog.Name__c;
        insert myrule;
        Ruleset__c  ruleset = new Ruleset__c();
        ruleset.RuleSet_Name__c = 'Child Ruleset';
        ruleset.Catalog_ID__c = catalog.Id;
        ruleset.Active__c = true;
        insert ruleset;
        rcontroller.catalogidToDel = Catalog.Id;
        ref = rcontroller.deleteCatalog();
        
        Catalog = new RuleSet_Catalog__c();
        rcontroller.Catalog = Catalog;
        ref = rcontroller.saveNewCatalog();
    }
}