DevOCL/src/objects/Active_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the active Ruleset Class Name. Updated automatically when a ruleset is activated or deactivated</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Active Rule</label>
</CustomObject>

DevOCL/src/classes/TestOpportunityTest_V0003.cls
@isTest
Public Class TestOpportunityTest_V0003
{
    Public static testMethod Opportunity setDummyValues()
    {
        Opportunity primaryObj = new Opportunity();
        primaryObj.name = 'Test';
        primaryObj.stagename = 'Qualification';
        primaryObj.closedate = System.Today();
        return primaryObj;
    }
    Public static testMethod Active_Rule__c setCustomSetting()
    {
        Active_Rule__c myrule = new Active_Rule__c();
        myrule.Name = 'Opportunity Test';
        myrule.Class_Name__c = 'OpportunityTest_V0003';
        insert myrule;
        return myrule;
    }
}