DevOCL/src/objects/Active_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the active Ruleset Class Name. Updated automatically when a ruleset is activated or deactivated</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Active Rule</label>
</CustomObject>

DevOCL/src/objects/RuleSet__c.object
<CustomObject>
    <description>RuleSet Catalog and Rule object are in a 1 to many relationship. Contains Version, Rule Definition (JSON) and Activity Status</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AsyncRequestID__c</fullName>
        <label>AsyncRequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Catalog_ID__c</fullName>
        <label>Catalog ID</label>
        <referenceTo>RuleSet_Catalog__c</referenceTo>
        <relationshipLabel>RuleSet</relationshipLabel>
        <relationshipName>RuleSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compile_Errors__c</fullName>
        <defaultValue>&apos;None&apos;</defaultValue>
        <label>Compile Errors</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Metadata_Container_Id__c</fullName>
        <label>Metadata Container Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Metadata_Container_UniqueId__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Metadata Container UniqueId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RuleSet_Name__c</fullName>
        <label>RuleSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compiled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compile Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>TestClassAsyncRequestID__c</fullName>
        <label>TestClassAsyncRequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Class_Body__c</fullName>
        <label>Test Class Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Test_Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Test Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Test_Class_Status__c</fullName>
        <defaultValue>&apos;Draft&apos;</defaultValue>
        <label>Test Class Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RuleSet</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>RuleSet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/objects/RuleSet_Catalog__c.object
<CustomObject>
    <description>RuleSet Catalog defines basic information about each rule, including e.g. Name, Effective Start Date, Effective End Date, and Active Version</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RuleSet Catalog</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Catalog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/RuleSetHomeController_V2.cls
/************************************************************************
* Name   : RuleSetHomeController_V2                                     *
* Author : Sujila R Nair                                                *
* Desc   : Controller for RulesHomePage_V2 page                         *
* ----------------------------------------------------------------------*
* Developer     |  Date        |  Description                           *
* ----------------------------------------------------------------------*
* Sujila R Nair |  04/22/2016  |  Original Version                      *
*************************************************************************/
public class RuleSetHomeController_V2 {
    public List<RuleSet__c> RulesetList {get;set;}
    public String rsidToDel {get;set;}                  
    public boolean showRulesetPanel {get;set;}
    public boolean showContextPanel {get;set;}
    public RuleSet_Catalog__c Catalog {get;set;}
    public String Fields;
    public String catalogName;
    
    public RuleSetHomeController_V2(){
        catalog = new RuleSet_Catalog__c();
        RulesetList = new List<RuleSet__c>();
        
    }
    
    public PageReference redirectCatalog(){
        if(ApexPages.currentPage().getParameters().get('id') !=null){
            Id catID = ApexPages.currentPage().getParameters().get('id');
            Fields = RulesUtilityClass.getFields(catID);
            catalog = Database.query('SELECT '+ fields+' FROM RuleSet_Catalog__c WHERE Id=\''+catID+'\'');
            catalogName = catalog.Name__c;
            Fields = RulesUtilityClass.getFieldsbyObject('Ruleset__c');
            RulesetList= Database.query('SELECT '+ fields+' FROM RuleSet__c WHERE Catalog_ID__c =\''+catalog.id+'\'');
            showRulesetPanel = true;
            showContextPanel = true;
            return null; 
        }
        else{
            PageReference pr = new Pagereference('/apex/RulesCatalogPage_V2');
            return pr;
        }
    }
    public Pagereference deleteRuleSet(){
        system.debug('I was called from deleteRuleSet with rsidToDel:' + rsidToDel);
        boolean deletedClass = false;
        if(rsidToDel != null){
            Id rid = id.valueOf(rsidToDel);
            List<RuleSet__c> TempRulesetList = [select id,active__c,Class_Name__c, Test_Class_Name__c from RuleSet__c where id =:rid ];
            if (TempRulesetList.size() > 0){
                if(TempRulesetList[0].active__c){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'<font color="red">Active Ruleset Can no be deleted</font>'));
                    return null;
                }else{
                    if(TempRulesetList[0].Class_Name__c != 'Not Available' || TempRulesetList[0].Class_Name__c != null){
                        deletedClass = deleteClassFile(TempRulesetList[0].Class_Name__c);
                        if(TempRulesetList[0].Test_Class_Name__c != 'Not Available')
                           deleteClassFile(TempRulesetList[0].Test_Class_Name__c);
                    }
                    system.debug('deletedClass'+deletedClass);
                    delete TempRulesetList[0];
                    system.debug('Ruleset deleted' + TempRulesetList[0]);
                    for(integer i=0; i< RulesetList.size();i ++){
                        if (RulesetList[i].id == TempRulesetList[0].id){
                            RulesetList.remove(i);
                            break;
                        }
                    }
                }
            }
        }
        else{
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Error,'<font color="red">Error in deleting Ruleset </font>'));
        }
        return null;
    }
    
    public Pagereference cloneRuleSet(){
        system.debug('I was called from cloneRuleSet with rsidToDel:' + rsidToDel);
        if(rsidToDel != null){
            Id rid = id.valueOf(rsidToDel);
            Fields = RulesUtilityClass.getFields(rid);
            Ruleset__c TempRuleset = Database.query('SELECT '+ fields+',Catalog_ID__r.Name__c FROM Ruleset__c WHERE Id=\''+rid+'\''); 
            Ruleset__c newRuleset = TempRuleset.clone(false,true,false,false);
            newRuleset.active__c = False;
            newRuleset.Class_Name__c = 'Not Available';
            newRuleset.Test_Class_Name__c = 'Not Available';
            newRuleset.Status__c = 'Draft';
            newRuleset.Compile_Errors__c = 'None';
            newRuleset.Compile_Errors__c = '';
            newRuleSet.Metadata_Container_Id__c = '';
            newRuleset.Metadata_Container_UniqueId__c = 0;
            newRuleset.AsyncRequestID__c = '';
            newRuleSet.RuleSet_Name__c = TempRuleset.Catalog_ID__r.Name__c;
            newRuleSet.Test_Class_Status__c = 'Draft';
            newRuleSet.Test_Class_Body__c = '';
            newRuleSet.TestClassAsyncRequestID__c = '';
            upsert newRuleset;
            Fields = RulesUtilityClass.getFieldsbyObject('Ruleset__c');
            RulesetList= Database.query('SELECT '+ fields+' FROM RuleSet__c WHERE Catalog_ID__c =\''+catalog.id+'\'');
        }
        return null;
    }
    
    public Pagereference navigateToHome(){
        Pagereference pr = new Pagereference('/apex/RulesCatalogPage_V2');
        return pr;
    }
    
    public Pagereference updateCatalog(){
        if(catalog.Id != null){
            upsert catalog;
            Active_Rule__c myrule = Active_Rule__c.getInstance(catalogName);
            if(myrule != null){
                myrule.Name = catalog.Name__c;
                update myrule;
                catalogName = catalog.Name__c;
            }
        }
        Fields = RulesUtilityClass.getFields(catalog.id);
        catalog = Database.query('SELECT '+ fields+' FROM RuleSet_Catalog__c WHERE Id=\''+catalog.id+'\'');
        return null;
    }
    
    private boolean deleteClassFile(String classname){
        List<apexclass> classes = [Select Id, name from ApexClass where Name=: classname limit 1];
        if(classes.size() > 0){
            HttpRequest req = new HttpRequest();
            req.setEndpoint(URL.getSalesforceBaseUrl().toExternalForm() + '/services/data/v36.0/sobjects/ApexClass/'+classes[0].id);
            req.setMethod('DELETE');
            req.setHeader('Authorization', 'OAuth ' + UserInfo.getSessionId());
            req.setHeader('Content-Type', 'application/json');
            Http httpreq = new Http();
            HttpResponse httpres = httpreq.send(req);
            if (httpres.getStatusCode() != 204) {
                System.debug(httpres.getBody());
                System.debug(httpres.toString());
                System.debug('STATUS_CODE:'+httpres.getStatusCode());
                System.debug('STATUS:'+httpres.getStatus());
                return false;
            }
        }
        return true;
    }
}