DevOCL/src/objects/Active_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the active Ruleset Class Name. Updated automatically when a ruleset is activated or deactivated</description>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Active Rule</label>
</CustomObject>

DevOCL/src/objects/RuleSet__c.object
<CustomObject>
    <description>RuleSet Catalog and Rule object are in a 1 to many relationship. Contains Version, Rule Definition (JSON) and Activity Status</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catalog_ID__c</fullName>
        <label>Catalog ID</label>
        <referenceTo>RuleSet_Catalog__c</referenceTo>
        <relationshipLabel>RuleSet</relationshipLabel>
        <relationshipName>RuleSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Class_Name__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Class Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RuleSet_Name__c</fullName>
        <label>RuleSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>RuleSet</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>RuleSet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/objects/RuleSet_Catalog__c.object
<CustomObject>
    <description>RuleSet Catalog defines basic information about each rule, including e.g. Name, Effective Start Date, Effective End Date, and Active Version</description>
    <fields>
        <fullName>Active_Class__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Active Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active_Version__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Active Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RuleSet Catalog</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Catalog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/TestRuleSetHomeController_V2.cls
@isTest
public class TestRuleSetHomeController_V2 {
    public static testmethod void testRuleSetHomeController(){
        PageReference ref = Page.RulesHomePage_V2;
        Test.setCurrentPage(ref);
        RuleSetHomeController_V2 rcontroller = new RuleSetHomeController_V2();
        ref = rcontroller.redirectCatalog();
        
        Ruleset_Catalog__c catalog = new RuleSet_Catalog__c();
        catalog.Name__c = 'Test Catalog';
        catalog.Active_Class__c = 'Not Available';
        catalog.Active_Version__c = 'Not Available';
        insert catalog;
        Ruleset__c ruleset = new Ruleset__c();
        ruleset.Catalog_ID__c = Catalog.id;
        ruleset.RuleSet_Name__c = catalog.Name__c;
        insert ruleset;
        Active_Rule__c myrule = new Active_Rule__c();
        myrule.Name = Catalog.Name__c;
        insert myrule;
        
        ApexPages.currentPage().getParameters().put('id', catalog.Id);
        ref = rcontroller.redirectCatalog();
        
        ref = rcontroller.updateCatalog();
        
        rcontroller.rsidToDel = ruleset.Id;
        ref = rcontroller.cloneRuleSet();
        ruleset.Class_Name__c =  'TestRuleSetHomeController_V2';
        update ruleset;
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new RulesMockHTTPResponseGenerator());
        Test.stopTest();
        ref = rcontroller.deleteRuleSet();
        
        ref = rcontroller.navigateToHome();
        
        ruleset = new Ruleset__c();
        ruleset.Catalog_ID__c = Catalog.id;
        ruleset.RuleSet_Name__c = catalog.Name__c;
        ruleset.Active__c = true;
        insert ruleset;
        rcontroller.rsidToDel = ruleset.Id;
        ref = rcontroller.deleteRuleSet();
        
        rcontroller.rsidToDel = null;
        ref = rcontroller.deleteRuleSet();
        
        ruleset = new Ruleset__c();
        ruleset.Class_Name__c = 'Not Available';
        ruleset.Catalog_ID__c = catalog.id;
        insert ruleset;
        Test.setMock(HttpCalloutMock.class, new RulesMockHTTPResponseGenerator());
        rcontroller.rsidToDel = ruleset.Id;
        ref = rcontroller.deleteRuleSet();
    }
}