DevOCL/src/objects/Active_Rule__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Manages the active Ruleset Class Name. Updated automatically when a ruleset is activated or deactivated</description>
    <label>Active Rule</label>
</CustomObject>

DevOCL/src/objects/RuleSet__c.object
<CustomObject>
    <description>RuleSet Catalog and Rule object are in a 1 to many relationship. Contains Version, Rule Definition (JSON) and Activity Status</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Catalog_ID__c</fullName>
        <label>Catalog ID</label>
        <referenceTo>RuleSet_Catalog__c</referenceTo>
        <relationshipLabel>RuleSet</relationshipLabel>
        <relationshipName>RuleSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>RuleSet</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>RuleSet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/objects/RuleSet_Catalog__c.object
<CustomObject>
    <description>RuleSet Catalog defines basic information about each rule, including e.g. Name, Effective Start Date, Effective End Date, and Active Version</description>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RuleSet Catalog</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Catalog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/RulesCatalogController_V2.cls
/************************************************************************
* Name   : RulesCatalogController_V2                                    *
* Author : Sujila R Nair                                                *
* Desc   : Controller for  RulesCatalogPage_V2 Page                     *
* ----------------------------------------------------------------------*
* Developer     |  Date        |  Description                           *
* ----------------------------------------------------------------------*
* Sujila R Nair |  04/22/2016  |  Original Version                      *
*************************************************************************/
public class RulesCatalogController_V2 {
    public String catalogidToDel {get;set;}
    public List<RuleSet_Catalog__c> allRulesCatalog {get;set;}
    public RuleSet_Catalog__c Catalog {get;set;}
    public String Fields;
 
    public RulesCatalogController_V2(){
        Fields = RulesUtilityClass.getFieldsbyObject('RuleSet_Catalog__c');
        allRulesCatalog = Database.query('SELECT '+ fields+' FROM RuleSet_Catalog__c');
        Catalog = new RuleSet_Catalog__c();
    }
    public Pagereference deleteCatalog(){
        system.debug('I was called from deleteCatalog' +catalogidToDel);
        if (catalogidToDel != null){
            List<Ruleset__c> childRulesets = [Select Id, Catalog_ID__c, Active__c 
                                              FROM  Ruleset__c 
                                              WHERE Catalog_ID__c =: Id.valueOf(catalogidToDel) AND Active__c =: true];
            if(childRulesets.size() == 0){
                RuleSet_Catalog__c catalog = [select id, name__c from  RuleSet_Catalog__c where id =: Id.valueOf(catalogidToDel)];
                Active_Rule__c myrule = Active_Rule__c.getInstance(catalog.Name__c);
                if(myrule != null){
                    delete myrule;
                }
                Database.delete(Id.valueOf(catalogidToDel));
                system.debug('Catalog Deleted');
            }
            else{
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.Info,'<font color="red">Catalog has an active rule. Deactivate the rule before deleting</font>'));
                return null;
            }
           
        }
        Fields = RulesUtilityClass.getFieldsbyObject('RuleSet_Catalog__c');
        allRulesCatalog = Database.query('SELECT '+ fields+' FROM RuleSet_Catalog__c');
        return null;
    }
    
    public Pagereference saveNewCatalog(){
        system.debug('I was called from saveNewCatalog'+ Catalog);
        Active_Rule__c myrule = new Active_Rule__c(); //Custom Setting
        if(catalog.Name__c != null){
            upsert Catalog;
            myrule.Name = catalog.Name__c;
            system.debug('MYRULE '+ myrule);
            upsert myrule;
            Pagereference pr = new Pagereference('/apex/RulesHomePage_V2?id='+catalog.Id);
            return pr;
        } 
        return null;
    }
}