DevOCL/src/objects/CLQ_Program_Transaction__c.object
<CustomObject>
    <description>This object is used to manage program applications</description>
    <fields>
        <fullName>CLQ_Submission_Date__c</fullName>
        <description>The date transaction was submitted</description>
        <label>Submission Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CLQ_Transaction_Status__c</fullName>
        <label>Transaction Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Submitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Reviewer Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Withdrawn by Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Application Revised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed by System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed at Applicant’s Request</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resubmitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approver Review In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/BatchDeleteProgramTrans.cls
global class BatchDeleteProgramTrans implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC){
    	//date noOfDays = 120;
    	
    	date todaysDate = system.today().adddays(-120);
    	string objq = 'select id,Name ,CreatedDate,CLQ_Transaction_Status__c,CLQ_Submission_Date__c from CLQ_Program_Transaction__c';
    	objq += ' WHERE CLQ_Submission_Date__c <=: todaysDate  and (CLQ_Transaction_Status__c=\'Not Submitted\' or CLQ_Transaction_Status__c=\'Not Complete\')';
    	system.debug('objq --->'+objq);
    	return Database.getQueryLocator(objq);
    }
    
    global void execute (Database.BatchableContext Bc,list<CLQ_Program_Transaction__c> lstTrans){
    	system.debug('lstTrans --->'+lstTrans);
    	if(!lstTrans.isEmpty()){
    		delete lstTrans;
    	}
    } 
    
    global void finish(Database.BatchableContext Bc){
    	
    }
}