DevOCL/src/objects/CLQ_OCLQS_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_OCLQS_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCLQS Configuration</label>
        <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_ProgramTriggerHandler.cls
/*Class Name : CLQ_ProgramTriggerHandler
* Description : This class contains all logic/methods used in CLQ_ProgramTrigger on CLQ_Program__c object
*/
public class CLQ_ProgramTriggerHandler{
    
    //Method to hold the logic for before insert on CLQ_Program__c object
    //@param : list<CLQ_Program__c> , map<id,CLQ_Program__c>
    //@return : none
    public static void beforeinsert(list<CLQ_Program__c> triggernew, map<id,CLQ_Program__c> triggernewMap){
        triggernew = populateConfigurationOnProgram(triggernew);
    }
    
    //Method to populate configuration record on Program while inserting
    //@param: list<CLQ_Program__c> new program record list
    //@return: list<CLQ_Program__c> updated program record list
    public static list<CLQ_Program__c> populateConfigurationOnProgram(list<CLQ_Program__c> triggernew){
        list<string> recordTypeNameList = new list<string>(); //list of record type name for all program record
        map<string,CLQ_OCLQS_Configuration__c> configurationnameRecordMap = new map<string,CLQ_OCLQS_Configuration__c>(); //map of all applicable configuration records with name as key  
        Map<ID,Schema.RecordTypeInfo> rt_Map = CLQ_Program__c.sObjectType.getDescribe().getRecordTypeInfosById(); //map to hold all the record type info for Program object

        //Store record type name value in recordTypeNameList
        for(CLQ_Program__c programRecord : triggernew){
            recordTypeNameList.add(rt_map.get(programRecord.recordTypeID).getName()); 
        }
        
        if(recordTypeNameList.size()>0){    
            //query the configuration records
            for(CLQ_OCLQS_Configuration__c configrecord : [SELECT id
                                                                , Name 
                                                           FROM CLQ_OCLQS_Configuration__c 
                                                           WHERE name IN :recordTypeNameList]){
                configurationnameRecordMap.put(configrecord.Name, configrecord);  //populate the map                                                  
            }
            
            
            for(CLQ_Program__c programRecord : triggernew){
                programRecord.CLQ_OCLQS_Configuration__c = (configurationnameRecordMap.get(rt_map.get(programRecord.recordTypeID).getName())).id; //populate the configuration record reference on program record
            }
        }
         return triggernew; // return the updated list 
    }
 
}