DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Email__c</fullName>
        <label>Program Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Number__c</fullName>
        <formula>IF(or(contains(RecordType.Name,&apos;FCC&apos;),RecordType.Name = &apos;Child Care Center&apos;,RecordType.Name = &apos;Out of State Registration&apos;,RecordType.Name = &apos;In-Home Aide&apos;,RecordType.Name = &apos;Day Camp&apos; ),&apos;2&apos;&amp;CLQ_Program_ID__c ,
 IF(or(RecordType.Name=&apos;Pre School&apos;,RecordType.Name=&apos;School Age Child Care&apos;),&apos;1&apos;&amp;CLQ_Program_ID__c,null))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Program Number</label>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program_Transaction__c.object
<CustomObject>
    <description>This object is used to manage program applications</description>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Number__c</fullName>
        <label>Program Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Role__c.object
<CustomObject>
    <description>Role of a contact in an organization</description>
    <fields>
        <fullName>CLQ_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Roles</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Role is a junction object between Program and Contact</description>
        <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Associated Individuals</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Role__c</fullName>
        <description>Role of a contact in an organization or program.</description>
        <inlineHelpText>Role of a contact in an organization or program.</inlineHelpText>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Administrator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Staff</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complainant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resident</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On-site Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Authorized Representative</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Transaction_Document__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Document_Status__c</fullName>
        <label>Document Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attached and Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Transaction</label>
        <referenceTo>CLQ_Program_Transaction__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_NotifyApplicant.cls
public with sharing class CLQ_NotifyApplicant {

   public list<CLQ_Program_Transaction__c>PTList;
   public list< CLQ_Transaction_Document__c>TDList=new list<CLQ_Transaction_Document__c>();
   public list< CLQ_Role__c>rolelist=new list<CLQ_Role__c>();
   ID PTid; 
   string emailadd;
   public String redirectUrl;
   list<string> emailids=new list<string>();
   String eBody;
   string eSubject;
   string tname;
   EmailTemplate emailtemplate;
   list<Messaging.SingleEmailMessage> maillist = new list<Messaging.SingleEmailMessage>();

 public pagereference notification(){

   PTid=ApexPages.currentPage().getParameters().get('id');
   CLQ_Program_Transaction__c PT = [select id,name,recordtypeid,recordtype.name,CLQ_Program__r.Recordtype.name,CLQ_Program__r.CLQ_Associated_Organization__r.name,CLQ_Program__r.name,CLQ_Program__r.CLQ_Associated_Organization__c,CLQ_Program__r.CLQ_Program_Number__c,CLQ_Program__r.CLQ_Program_Email__c from CLQ_Program_Transaction__c where id=:PTid];
   TDList = [select id,name,CLQ_Document_Status__c,CLQ_Program_Transaction__c from CLQ_Transaction_Document__c where CLQ_Program_Transaction__c =:PTid and CLQ_Document_Status__c='Returned for Revision'];
   system.debug('MMMMMMM'+TDList.size());
   rolelist=[select id,name,CLQ_Contact__c,CLQ_Contact__r.email,CLQ_Program__c from CLQ_Role__c where CLQ_Program__c =:PT.CLQ_Program__r.id];
  
     if(TDList.size()>0){
        System.debug('MMMMMM'+PT.CLQ_Program__r.Recordtype.name);
        if(PT.CLQ_Program__r.Recordtype.name == 'Child Care Center'||PT.CLQ_Program__r.Recordtype.name.contains('FCC')){
        if(rolelist.size()>0){
            for(CLQ_Role__c role : rolelist){
          emailadd=role.CLQ_Contact__r.email;
         }
        }
        system.debug('MMMMMM'+emailadd);
        if(emailadd !=null)
        emailids.add(emailadd);
       emailids.add(PT.CLQ_Program__r.CLQ_Program_Email__c);
       system.debug('MMMMMM'+emailids);
       emailtemplate=[Select e.id, e.markup, e.subject, e.body,e.HtmlValue from emailtemplate e where developername='CLQ_NotifyApplicant_ODJFS'];
       eBody = emailtemplate.Body;
       ebody = ebody.replace('{!CLQ_Program__c.Name}',PT.CLQ_Program__r.name);
       ebody = ebody.replace('{!CLQ_Program__c.CLQ_Program_Number__c}',PT.CLQ_Program__r.CLQ_Program_Number__c);
       eSubject = emailtemplate.subject;
       esubject = esubject.replace('{!CLQ_Program__c.Name}',PT.CLQ_Program__r.name);
       esubject = esubject.replace('{!CLQ_Program__c.CLQ_Program_Number__c}',PT.CLQ_Program__r.CLQ_Program_Number__c);
       esubject = esubject.replace('{!CLQ_Program_Transaction__c.RecordTypeId}',PT.recordtype.name);
       esubject = esubject.replace('{!CLQ_Program__c.CLQ_Associated_OrganizationId__c}',PT.CLQ_Program__r.CLQ_Associated_Organization__c);
       tname='';
       for(CLQ_Transaction_Document__c TD : TDList){
        
         if(tname!=null && tname!='')
         tname= tname+','+TD.name;
         else
           tname=td.name;
           system.debug('MMMMM'+tname);
          }
      ebody = ebody.replace('{!CLQ_Transaction_Document__c.Name}',tname);
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 

                 Mail.setToAddresses(emailids);
                 Mail.setPlaintextBody(ebody);        
                 Mail.SetSubject(esubject);
                 Mail.setReplyTo('noreply@salesforce.com');
                 //mail.setUseSignature(false);
                 Mail.setSenderDisplayName('OCLQS');   
                 maillist.add(mail);
           
           system.debug('MMMMMMM'+maillist.size());

      if(maillist!=null && maillist.size()>0){
         Messaging.sendEmailResult[] EmailResult=Messaging.sendEmail(maillist,false);
         system.debug('MMMMM'+emailresult);
      }
    }
    
   if(PT.CLQ_Program__r.Recordtype.name.contains('School')){
        if(rolelist.size()>0){
            for(CLQ_Role__c role : rolelist){
          emailadd=role.CLQ_Contact__r.email;
         }
        }
        system.debug('MMMMMM'+emailadd);
        if(emailadd !=null)
        emailids.add(emailadd);
       emailids.add(PT.CLQ_Program__r.CLQ_Program_Email__c);
       system.debug('MMMMMM'+emailids);
       emailtemplate=[Select e.id, e.markup, e.subject, e.body,e.HtmlValue from emailtemplate e where developername='CLQ_NotifyApplicant_ODE'];
       eBody = emailtemplate.Body;
       ebody = ebody.replace('{!CLQ_Program__c.Name}',PT.CLQ_Program__r.name);
       ebody = ebody.replace('{!CLQ_Program__c.CLQ_Program_Number__c}',PT.CLQ_Program__r.CLQ_Program_Number__c);
       eSubject = emailtemplate.subject;
       esubject = esubject.replace('{!CLQ_Program__c.Name}',PT.CLQ_Program__r.name);
       esubject = esubject.replace('{!CLQ_Program__c.CLQ_Program_Number__c}',PT.CLQ_Program__r.CLQ_Program_Number__c);
       esubject = esubject.replace('{!CLQ_Program_Transaction__c.RecordTypeId}',PT.recordtype.name);
       esubject = esubject.replace('{!CLQ_Program__c.CLQ_Associated_Organization__c}',PT.CLQ_Program__r.CLQ_Associated_Organization__c);
       tname='';
       for(CLQ_Transaction_Document__c TD : TDList){
        
         if(tname!=null && tname !='')
         tname= tname+','+TD.name;
         else
           tname=td.name;
           system.debug('MMMMM'+tname);
          }
      ebody = ebody.replace('{!CLQ_Transaction_Document__c.Name}',tname);
      ebody = ebody.replace('{!CLQ_Program__c.CLQ_Associated_Organization__c}',PT.CLQ_Program__r.CLQ_Associated_Organization__r.name);
      Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage(); 

                 Mail.setToAddresses(emailids);
                 Mail.setPlaintextBody(ebody);        
                 Mail.SetSubject(esubject);
                 Mail.setReplyTo('noreply@salesforce.com');
                 //mail.setUseSignature(false);
                 Mail.setSenderDisplayName('OCLQS');   
                 maillist.add(mail);
           
           system.debug('MMMMMMM'+maillist.size());

      if(maillist!=null && maillist.size()>0){
         Messaging.sendEmailResult[] EmailResult=Messaging.sendEmail(maillist,false);
         system.debug('MMMMM'+emailresult);
      }
    }
  }
     redirecturl ='/'+PT.id;
     pageReference newpage=new pagereference(redirecturl);
     newpage.setRedirect(true);
     return newpage;
 }

}