DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_County__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>County</label>
        <referenceTo>CLQ_County__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Estimated_Enrollment__c</fullName>
        <label>Estimated Enrollment</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Food_Service__c</fullName>
        <inlineHelpText>Which of the following has been obtained?</inlineHelpText>
        <label>Food Service</label>
        <picklist>
            <picklistValues>
                <fullName>Food Service License</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service License Exemption</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Full_Day_Option__c</fullName>
        <globalPicklist>Yes_No</globalPicklist>
        <label>Full-day Option</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Funding__c</fullName>
        <label>Funding</label>
        <picklist>
            <picklistValues>
                <fullName>Local</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Registration_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed/Certified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Type__c</fullName>
        <inlineHelpText>Type of license issued</inlineHelpText>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuous</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_OCLQS_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCLQS Configuration</label>
        <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Open_Date__c</fullName>
        <description>Only Future Date</description>
        <label>Open Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CLQ_State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>OH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KY</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MI</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NH</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Total_Staff__c</fullName>
        <inlineHelpText>Total Number of Staff at this Program</inlineHelpText>
        <label>Total Staff</label>
        <precision>9</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program_Transaction__c.object
<CustomObject>
    <description>This object is used to manage program applications</description>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_City__c</fullName>
        <formula>CLQ_Program__r.CLQ_City__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_County__c</fullName>
        <formula>CLQ_Program__r.CLQ_County__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>County</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Estimated_Enrollment__c</fullName>
        <label>Estimated Enrollment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Food_Service__c</fullName>
        <label>Food Service</label>
        <picklist>
            <picklistValues>
                <fullName>Food Service License</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Food Service License Exemption</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Registration_Status__c</fullName>
        <label>License / Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Licensed/Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_State__c</fullName>
        <formula>TEXT(CLQ_Program__r.CLQ_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Transaction_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program_Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Zip_Code__c</fullName>
        <formula>CLQ_Program__r.CLQ_Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zip Code</label>
        <type>Text</type>
    </fields>
    <label>Program Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Role__c.object
<CustomObject>
    <description>Role of a contact in an organization</description>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Role is a junction object between Program and Contact</description>
        <inlineHelpText>Role is a junction object between Program and Contact</inlineHelpText>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Associated Individuals</relationshipLabel>
        <relationshipName>Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Role</label>
    <nameField>
        <displayFormat>Role-{00000000}</displayFormat>
        <label>Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Transaction_Document__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Document_Status__c</fullName>
        <label>Document Status</label>
        <picklist>
            <picklistValues>
                <fullName>Attached and Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reviewed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Returned for Revision</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Submitted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Transaction</label>
        <referenceTo>CLQ_Program_Transaction__c</referenceTo>
        <relationshipLabel>Transaction Documents</relationshipLabel>
        <relationshipName>Transaction_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction Document</label>
    <nameField>
        <label>Transaction Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transaction Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_TransDoctest.cls
@istest
private class CLQ_TransDoctest {
    
    static testMethod void thisTest (){
    //insert configuration record
    list<CLQ_OCLQS_Configuration__c> configurationRecordList = new list<CLQ_OCLQS_Configuration__c>();
    CLQ_OCLQS_Configuration__c configRecordTypeA = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type A Home');
    CLQ_OCLQS_Configuration__c configRecordCCC = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
    CLQ_OCLQS_Configuration__c configRecordschool = new CLQ_OCLQS_Configuration__c(Name = 'Pre School');
    configurationRecordList.add(configRecordTypeA);
    configurationRecordList.add(configRecordCCC);
    configurationRecordList.add(configRecordschool);
    insert configurationRecordList;
    
    Account A = new Account(Name='Test account');
    insert A;
        CLQ_County__c C = new CLQ_County__c(Name='Franklin');
    insert C;
        CLQ_Program__c P = new CLQ_Program__c(Name = 'Test Prog',CLQ_Open_Date__c=date.today()+2,CLQ_Associated_Organization__c=A.id,CLQ_License_Registration_Status__c ='excempt',CLQ_License_Type__c='Continous',
                                               CLQ_Total_Staff__c=5,CLQ_Estimated_Enrollment__c=9,CLQ_Full_Day_Option__c='No',CLQ_Funding__c='Local',CLQ_Food_Service__c='Food Service License',CLQ_Street_Address_1__c='392 western ave',
                                               CLQ_City__c='chicago',CLQ_State__c='Illinois',Recordtypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByName().get('Child Care Center').getRecordTypeId(),
                                               CLQ_Zip_Code__c='98780',CLQ_County__c=c.id);
    insert P;
      CLQ_Program__c P1 = new CLQ_Program__c(Name = 'Test Prog1',CLQ_Open_Date__c=date.today()+2,CLQ_Associated_Organization__c=A.id,CLQ_License_Registration_Status__c ='excempt',CLQ_License_Type__c='Continous',
                                               CLQ_Total_Staff__c=5,CLQ_Estimated_Enrollment__c=9,CLQ_Full_Day_Option__c='No',CLQ_Funding__c='Local',CLQ_Food_Service__c='Food Service License',CLQ_Street_Address_1__c='392 western ave',
                                               CLQ_City__c='chicago',CLQ_State__c='Illinois',Recordtypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByName().get('Pre School').getRecordTypeId(),
                                               CLQ_Zip_Code__c='98780',CLQ_County__c=c.id);
    insert P1;
        CLQ_Program_Transaction__c PT = new CLQ_Program_Transaction__c(CLQ_Transaction_Assigned_To__c=UserInfo.getUserid(),CLQ_Program__c=p.id);
        
    insert PT;
        CLQ_Program_Transaction__c PT1 = new CLQ_Program_Transaction__c(CLQ_Transaction_Assigned_To__c=UserInfo.getUserid(),CLQ_Program__c=p1.id);
        
    insert PT1;
        CLQ_Transaction_Document__c TD = new CLQ_Transaction_Document__c(Name = 'Test',CLQ_Document_Status__c='Returned for Revision',CLQ_Program_Transaction__c=PT.id);
     
     insert TD;
        CLQ_Transaction_Document__c TD1 = new CLQ_Transaction_Document__c(Name = 'Test1',CLQ_Document_Status__c='Returned for Revision',CLQ_Program_Transaction__c=PT1.id);
     
     insert TD1;
       CLQ_Role__c Role = new CLQ_Role__c(CLQ_Program__c = p.id);
     insert role;
       CLQ_Role__c Role1 = new CLQ_Role__c(CLQ_Program__c = p1.id);
     insert role1;
     emailmessage em = new emailmessage();
                em.fromaddress = 'Test@test.com';
                em.toaddress = 'test1@test.com';
                em.subject = 'Test Email';
                em.textbody = 'testing';
                //em.parentid = t1.id;
     
     Test.startTest();    
     //Test.setCurrentPage(new pageReference('/apex/CLQTransDocApprovedPage'));
     //System.currentPageReference().getParameters().put('id',TD.id);
     //CLQTransDocApprove App = new CLQTransDocApprove();
     //App.statusupdateApp(); //Commented out by Vrajesh as there is no CLQTransDocApprove class now : Date:07/13/2016
     //Test.setCurrentPage(new pageReference('/apex/CLQTransDocRevisionPage'));
     //System.currentPageReference().getParameters().put('id',TD.id);
     //CLQTransDocreturnForRevision Rev=new CLQTransDocreturnForRevision();
     //Rev.statusupdate(); //Commented out by Vrajesh as there is no CLQTransDocreturnForRevision class now : Date:07/13/2016
     Test.setCurrentPage(new pageReference('/apex/CLQ_NotifyApplicantPage'));
     System.currentPageReference().getParameters().put('id',PT.id);
     CLQ_NotifyApplicant NOtify=new CLQ_NotifyApplicant();
     Notify.notification();
    insert em;
    Test.setCurrentPage(new pageReference('/apex/CLQ_NotifyApplicantPage'));
     System.currentPageReference().getParameters().put('id',PT1.id);
     CLQ_NotifyApplicant NOtify1=new CLQ_NotifyApplicant();
     Notify1.notification();
    //insert em;
     
     test.stoptest();
    }
}