DevOCL/src/objects/CLQ_OCLQS_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Licensing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_OCLQS_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCLQS Configuration</label>
        <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space__c.object
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <fields>
        <fullName>CLQ_Number_of_Children_Under_2_5__c</fullName>
        <label>Number of Children Under 2 1/2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Number_of_Children_Under_2__c</fullName>
        <label>Number of Children Under 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <formula>CLQ_Program__r.CLQ_Street_Address_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Used_By_Under_or_Over_2__c</fullName>
        <label>Used by Under or Over 2</label>
        <picklist>
            <picklistValues>
                <fullName>Under</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Used_by_Under_or_Over_2_1_2__c</fullName>
        <label>Used by Under or Over 2 1/2</label>
        <picklist>
            <picklistValues>
                <fullName>Under</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_CreateInspectionExtensionTest.cls
/* Name : CLQ_CreateInspectionExtensionTest
* Description : This class/extension contains all test methods for CLQ_CreateInspectionExtension class. 
* CLQ_CreateInspectionExtension 96%
* CLQ_UtilityClass 100%
**/
@isTest
private class CLQ_CreateInspectionExtensionTest {
    
    @isTest static void test_onLoad() {

         Case caseRecord = prepareTestData();
         insert caseRecord; 
        //Test start
        Test.startTest();
        PageReference pageRef = Page.CLQ_CreateInspection;
        pageRef.getParameters().put('id',caseRecord.id);

        //Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        CLQ_CreateInspectionExtension extensionObject = new CLQ_CreateInspectionExtension(controller);
        extensionObject.onLoad();
        extensionObject.onOK();
        Test.stopTest();

    }
    
    //Method to do negative testing
    @isTest static void test_validationTest() {
         Case caseRecord = prepareTestData(); 
         caseRecord.CLQ_No_Investigation_Required__c = true;
                 caseRecord.CLQ_Reason_for_No_Investigation__c ='test'; 
         insert caseRecord;
        // Implement test code
        //Test start
        Test.startTest();
        PageReference pageRef = Page.CLQ_CreateInspection;
        pageRef.getParameters().put('id',caseRecord.id);

        //Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController controller = new ApexPages.StandardController(caseRecord);
        CLQ_CreateInspectionExtension extensionObject = new CLQ_CreateInspectionExtension(controller);
        extensionObject.onLoad();
        
        Test.stopTest();
    }

    //Method to prepare the data
    public static case prepareTestData(){
                //insert configuration record
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
        
        //Create account record
        Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
        insert accountrecord ;
        
        //Insert contact
        Contact contactrecord = new Contact(Firstname='test', lastName = 'Test',Accountid = accountrecord.id,Email='test@clq.com' );
        insert contactrecord ;
        
        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByName().get('FCC - Type B Home').getRecordTypeId();
        programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserid();
        insert programRecord ;
        
        //Create Room Space record
        CLQ_Room_Space__c roomSpace = new CLQ_Room_Space__c();
        roomSpace.CLQ_Program__c = programRecord.id;
        roomSpace.CLQ_Number_of_Children_Under_2__c = 2;
        roomSpace.CLQ_Used_By_Under_or_Over_2__c = 'Both';
        //roomSpace.CLQ_Number_of_Children_Under_2_5__c = 2 ;
        //roomSpace.CLQ_Used_by_Under_or_Over_2_1_2__c = 'Under';
        insert roomSpace;

        //Insert case for program
        Case caseRecord = new Case();
        caseRecord.recordTypeID = Schema.SObjectType.Case.getRecordTypeInfosByName().get('Complaint').getRecordTypeId();
        caseRecord.ContactId = contactrecord.id;
        caseRecord.CLQ_Program__c = programRecord.id;
        caseRecord.CLQ_Approver_s_Email__c = 'test@CLQ.com';
        caseRecord.CLQ_Assigned_to_Email__c = 'test@CLQ.com'; 
        caseRecord.CLQ_Intake_Date__c = Date.today();
        caseRecord.CLQ_Assigned_To__c = UserInfo.getUserid();
        //insert caseRecord;
         
        return caseRecord;  
    }
}