DevOCL/src/objects/CLQ_Inspection__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Approved_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Approved By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Inspections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space__c.object
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <fields>
        <fullName>CLQ_Inspection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/Visit_Information__c.object
<CustomObject>
    <fields>
        <fullName>Inspection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipLabel>Visit Information</relationshipLabel>
        <relationshipName>Visit_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Onsite Worker</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Visit_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Visit Information</label>
    <nameField>
        <label>Visit Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visit Information</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/TestVisitInfo.cls
@isTest
private class TestVisitInfo {
    static testMethod void mytest(){
        CLQ_Inspection__c objCLQIns = new CLQ_Inspection__c(CLQ_Approved_By__c = userinfo.getUserID());
        insert objCLQIns;
        Visit_Information__c objVisit = new Visit_Information__c(User__c = Userinfo.getUserId(),Name = 'Test Visit',Inspection__c = objCLQIns.id);
        insert objVisit;
        CLQ_Room_Space__c objRoom = new CLQ_Room_Space__c(CLQ_Inspection__c = objCLQIns.id,Name='TestRooms');
        insert objRoom;
        Visit_Information__c objVisit1 = new Visit_Information__c(User__c = Userinfo.getUserId(),Name = 'Test Visit',Inspection__c = objCLQIns.id);
        insert objVisit1;
    }

}