DevOCL/src/objects/CLQ_Inspection__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Inspection_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>InspectionOwner</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Assigned_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Licensor/specialist assigned to the program.</inlineHelpText>
        <label>Assigned Reviewer / Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Registration_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed/Certified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Type__c</fullName>
        <inlineHelpText>Type of license issued</inlineHelpText>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuous</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Status__c</fullName>
        <label>Program Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed by System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enforcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space__c.object
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <fields>
        <fullName>CLQ_Inspection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space_Inspection__c.object
<CustomObject>
    <description>Junction object between Room/Space and Inspection</description>
    <fields>
        <fullName>CLQ_Inspection__c</fullName>
        <label>Inspection</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipLabel>Rooms/Space Inspection</relationshipLabel>
        <relationshipName>Rooms_Space_Inspection</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipName>Rooms_Spaces_Inspection</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Room/Space Inspection</label>
    <nameField>
        <displayFormat>RSI-{000000}</displayFormat>
        <label>Room/Space Inspection Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms/Space Inspection</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_CreateProgramInspectionExtn.cls
/* Name : CLQ_CreateProgramInspectionExtn
* Developer Name : Vrajesh Sheth
* Date : 07/19/2016
* Email : vsheth@incapsulate.com
* Description : This class/extension contains all detail logic/methods for CLQ_CreateProgramInspection pages. 
*			It will create a new inspection record from program record 
* V1 - Date: 07/19/2016 - Started development
**/
public with sharing class CLQ_CreateProgramInspectionExtn {
	//variables
    public list<String> fieldlist;
    public CLQ_Program__c programRecord;

    //Constructor
	public CLQ_CreateProgramInspectionExtn(ApexPages.StandardController controller) {
		fieldlist = new list<String>{'CLQ_Assigned_Reviewer__c','CLQ_License_Registration_Status__c','CLQ_Program_Status__c','CLQ_License_Type__c'};
		if(!Test.isRunningTest()){
            controller.addFields(fieldlist);
        }
        this.programRecord = (CLQ_Program__c)controller.getRecord();
	}

	//Method to create inspection record onload 
	//@param: none
	//@return: pageReference 
	public pageReference onLoad(){
		//1. Create inspection record for given complaint
		CLQ_Inspection__c inspectionrecord = new CLQ_Inspection__c();
		if(programRecord.CLQ_License_Registration_Status__c == 'Licensed' 
			&& programRecord.CLQ_Program_Status__c == 'Open'){
			if(programRecord.CLQ_License_Type__c == 'Continuous'){
				inspectionrecord = CLQ_UtilityClass.createInspectionrecord('Annual', 'Full', 'Pending Processing');	
			}
			if(programRecord.CLQ_License_Type__c == 'Provisional'){
				inspectionrecord = CLQ_UtilityClass.createInspectionrecord('Provisional', 'Full', 'Pending Processing');
			}
		}
		
		
        inspectionrecord.CLQ_Program__c = programRecord.id;
        inspectionrecord.CLQ_Inspection_Owner__c = UserInfo.getUserId();
        insert inspectionrecord;
		
        //2. Copy all Room/Space records to inspection
        list<CLQ_Room_Space__c> roomSpaceList = new list<CLQ_Room_Space__c>();
        if(programRecord.id != null){
        	roomSpaceList = CLQ_UtilityClass.queryRoomSpacefromProgram(programRecord.id);
           	if(roomSpaceList.size()>0){
           		list<CLQ_Room_Space_Inspection__c> roomSpaceInspectionList = CLQ_UtilityClass.createRoomSpaceInspection(roomSpaceList , inspectionrecord);
                insert roomSpaceInspectionList;
            }                    
        }

        //3. Insert task record
        insert CLQ_UtilityClass.createTaskrecord(programRecord.CLQ_Assigned_Reviewer__c, inspectionrecord.Id, (Date.today()).adddays(20), 'Inspection Review task', 'Inspection Review task');
    
		return CLQ_UtilityClass.redirecttoPage('/'+inspectionrecord.Id);
	}

	//Method to redirect to Case detail page
    //@param : none
    //@return : Pagereference
    public pagereference onOK(){
        return CLQ_UtilityClass.redirecttoPage('/'+programRecord.Id);
    }
}