DevOCL/src/objects/CLQ_OCLQS_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Assigned_Reviewer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Licensor/specialist assigned to the program.</inlineHelpText>
        <label>Assigned Reviewer / Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_First_Inspection_Due__c</fullName>
        <inlineHelpText>First/Next Provisional/Annual Inspection Due Date</inlineHelpText>
        <label>Next Inspection Due</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Issue_Date__c</fullName>
        <inlineHelpText>Date of issuance of license.</inlineHelpText>
        <label>License Begin Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Registration_Status__c</fullName>
        <label>License Status</label>
        <picklist>
            <picklistValues>
                <fullName>Exempt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Licensed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Licensed/Certified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_License_Type__c</fullName>
        <inlineHelpText>Type of license issued</inlineHelpText>
        <label>License Type</label>
        <picklist>
            <picklistValues>
                <fullName>Provisional</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Continuous</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Licensing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_OCLQS_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCLQS Configuration</label>
        <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Status__c</fullName>
        <label>Program Status</label>
        <picklist>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed by System</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enforcement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Suspended</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space__c.object
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <fields>
        <fullName>CLQ_Number_of_Children_Under_2__c</fullName>
        <label>Number of Children Under 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <formula>CLQ_Program__r.CLQ_Street_Address_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Used_By_Under_or_Over_2__c</fullName>
        <label>Used by Under or Over 2</label>
        <picklist>
            <picklistValues>
                <fullName>Under</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_CreateProgramInspectionExtnTest.cls
/* Name : CLQ_CreateProgramInspectionExtnTest
* Developer Name : Vrajesh Sheth
* Date : 07/19/2016
* Email : vsheth@incapsulate.com
* Description : This class/extension contains all test methods for CLQ_CreateProgramInspectionExtn class. 
* V1 - Date: 07/19/2016 - Started development

**/
@isTest
private class CLQ_CreateProgramInspectionExtnTest {
	
	@isTest static void testAllMethods() {
		// Implement test code
		CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
                
        //Create account record
        Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
        insert accountrecord ;
                
        //Insert contact
        Contact contactrecord = new Contact(Firstname='test', lastName = 'Test',Accountid = accountrecord.id );
        insert contactrecord ;
                
        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByName().get('FCC - Type B Home').getRecordTypeId();
        programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserid();
        programRecord.CLQ_Program_Status__c = 'Open';
        programRecord.CLQ_License_Registration_Status__c = 'Licensed';
        programRecord.CLQ_License_Type__c = 'Continuous';
        programRecord.CLQ_License_Issue_Date__c = Date.today();
        programRecord.CLQ_First_Inspection_Due__c = Date.today().adddays(20);
        insert programRecord ;

        //Create Room Space record
        CLQ_Room_Space__c roomSpace = new CLQ_Room_Space__c();
        roomSpace.CLQ_Program__c = programRecord.id;
        roomSpace.CLQ_Number_of_Children_Under_2__c = 2;
        roomSpace.CLQ_Used_By_Under_or_Over_2__c = 'Both';
        insert roomSpace;

        Test.startTest();
        PageReference pageRef = Page.CLQ_CreateProgramInspection;
        pageRef.getParameters().put('id',programRecord.id);

        //Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController controller = new ApexPages.StandardController(programRecord);
        CLQ_CreateProgramInspectionExtn extensionObject = new CLQ_CreateProgramInspectionExtn(controller);
        extensionObject.programRecord = [SELECT id
        								,CLQ_Assigned_Reviewer__c
        								,CLQ_License_Registration_Status__c
        								,CLQ_Program_Status__c
        								,CLQ_License_Type__c
        								FROM CLQ_Program__c
        								WHERE id =:programRecord.id];

        extensionObject.onLoad();
        extensionObject.onOK();
        Test.stopTest();
	}
	
	
}