DevOCL/src/objects/CLQ_Domain__c.object
<CustomObject>
    <description>Object to store the domain information for inspection rules</description>
    <label>Domain</label>
    <nameField>
        <label>Domain Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Domains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Findings__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CLQ_Risk_Level__c</fullName>
        <formula>TEXT(CLQ_Standard_Finding__r.CLQ_Risk_Level__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Risk Level</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Rules_Inspected__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rules Inspected</label>
        <referenceTo>CLQ_Rules_Inspected__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Standard_Finding__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Standard Finding</label>
        <referenceTo>CLQ_Standard_Findings__c</referenceTo>
        <relationshipLabel>Findings</relationshipLabel>
        <relationshipName>Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Findings</label>
    <nameField>
        <displayFormat>Findings-{000000}</displayFormat>
        <label>Findings No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Findings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Inspection__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <formula>CLQ_Program__r.CLQ_Street_Address_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Use_Rules_Effective_On__c</fullName>
        <label>Use Rules Effective On</label>
        <type>Date</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Inspection_Tools__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLQ_Applicable_To__c</fullName>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Alleged Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Care Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Home Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of State Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Age Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCC - Type A Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCC - Type B Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type A Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type B Home</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Inspection Tools</label>
    <nameField>
        <label>Inspection Tools Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_OCLQS_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Licensing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_OCLQS_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCLQS Configuration</label>
        <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Rule__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Applicable_To__c</fullName>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Alleged Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Care Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Home Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of State Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Age Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type A Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type B Home</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Domain__c</fullName>
        <label>Domain</label>
        <picklist>
            <picklistValues>
                <fullName>Staff Files (FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Written Policies &amp; Procedures(FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indoor-Outdoor Space(FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health &amp; Safety (FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Safe &amp; Sanitary Envt (RST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Program Info(FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Children&apos;s Files (FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Postings &amp; Equipment (RST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ratio Info (FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Observations (RST)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>License &amp; Approvals(FT)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diapering &amp; InfantCare(FT)</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Rule_Effective_Date__c</fullName>
        <label>Rule Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CLQ_Rule_Expiration_Date__c</fullName>
        <label>Rule Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Rule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Rules_Inspected__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Inspection_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection No</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipLabel>Rules Inspected</relationshipLabel>
        <relationshipName>Rules_Inspected</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rule</label>
        <referenceTo>CLQ_Rule__c</referenceTo>
        <relationshipLabel>Rules Inspected</relationshipLabel>
        <relationshipName>Rules_Inspected</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rules Inspected</label>
    <nameField>
        <displayFormat>RI#-{000000}</displayFormat>
        <label>Rules Inspected No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Inspected</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Standard_Findings__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CLQ_Finding_Code__c</fullName>
        <description>Unique Code per associated with the finding</description>
        <label>Finding Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Risk_Level__c</fullName>
        <label>Risk Level</label>
        <picklist>
            <picklistValues>
                <fullName>Serious</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Moderate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Rules__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rules</label>
        <referenceTo>CLQ_Rule__c</referenceTo>
        <relationshipLabel>Standard Findings</relationshipLabel>
        <relationshipName>Standard_Findings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Standard Findings</label>
    <nameField>
        <label>Standard Finding</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Standard Findings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Tools_Rules__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Visit Tool and Rules objects</description>
    <fields>
        <fullName>CLQ_Inspection_Tools__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection Tools</label>
        <referenceTo>CLQ_Inspection_Tools__c</referenceTo>
        <relationshipLabel>Tools Rules</relationshipLabel>
        <relationshipName>Tools_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Rules__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Rules</label>
        <referenceTo>CLQ_Rule__c</referenceTo>
        <relationshipLabel>Tools Rules</relationshipLabel>
        <relationshipName>Tools_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tools Rules</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Tools Rules No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_VisitModeController_Test.cls
@isTest
private class CLQ_VisitModeController_Test {
	
	@isTest static void test_method_one() {
	
        CLQ_Inspection__c inspectionrecord = prepareData();
        CLQ_Rules_Inspected__c ruleInspected = [SELECT id,CLQ_Rule__c FROM CLQ_Rules_Inspected__c Limit 1];
        Test.startTest();
        PageReference pageRef = Page.CLQ_VisitMode;
        pageRef.getParameters().put('id',inspectionrecord.id); 
        pageRef.getParameters().put('selectedInspectedRule',ruleInspected.id); 
        pageRef.getParameters().put('selectedRule',ruleInspected.CLQ_Rule__c); 
        //Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController controller = new ApexPages.StandardController(inspectionrecord);
        CLQ_VisitModeController extensionObject = new CLQ_VisitModeController(controller);
        
        extensionObject.onLoad();
        extensionObject.onSearch();
        extensionObject.domainfiltervalue = 'Staff Files (FT)';	
        extensionObject.filtervalue = 'Not Assessed';								
        extensionObject.onSearch();

        extensionObject.onCancel();
        extensionObject.updateFindingDescription();
        
        extensionObject.popupOnLoad();
        extensionObject.closePopUp();
        extensionObject.savePopUp();
        extensionObject.onSaveandClose();
        Test.stopTest();
	}

        @isTest static void test_markAllCompliant() {
        
        CLQ_Inspection__c inspectionrecord = prepareData();
        CLQ_Rules_Inspected__c ruleInspected = [SELECT id,CLQ_Rule__c FROM CLQ_Rules_Inspected__c Limit 1];
        Test.startTest();
        PageReference pageRef = Page.CLQ_VisitMode;
        pageRef.getParameters().put('id',inspectionrecord.id); 
        pageRef.getParameters().put('selectedInspectedRule',ruleInspected.id); 
        pageRef.getParameters().put('selectedRule',ruleInspected.CLQ_Rule__c); 
        //Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController controller = new ApexPages.StandardController(inspectionrecord);
        CLQ_VisitModeController extensionObject = new CLQ_VisitModeController(controller);
        
        extensionObject.onLoad();
        extensionObject.onSearch();
        extensionObject.domainfiltervalue = 'Staff Files (FT)'; 
        extensionObject.filtervalue = 'Not Assessed';                                                           
        extensionObject.markAllCompliant();

        extensionObject.onCancel();
        extensionObject.updateFindingDescription();
        
        extensionObject.popupOnLoad();
        extensionObject.closePopUp();
        extensionObject.savePopUp();
        extensionObject.onSaveandClose();
        Test.stopTest();
        }
	
	public static CLQ_Inspection__c prepareData(){
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'Child Care Center');
        insert configRecord; 
        
        //Create account record
        Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
        insert accountrecord ;
        
        //Insert contact
        Contact contactrecord = new Contact(Firstname='test', lastName = 'Test',Accountid = accountrecord.id );
        insert contactrecord ;
        
        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByName().get('Child Care Center').getRecordTypeId();
        programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserid();
        insert programRecord ;
        
       

        //Insert CLQ_Inspection__c 
        CLQ_Inspection__c inspectionrecord = CLQ_UtilityClass.createInspectionrecord('Pre-license', 'Full', 'Pending Processing');
        inspectionrecord.CLQ_Program__c = programRecord.id;
        inspectionrecord.CLQ_Use_Rules_Effective_On__c = Date.today();
        insert inspectionrecord;

        //Create Rules
        list<CLQ_Rule__c> ruleList = new list<CLQ_Rule__c>();
        CLQ_Rule__c rule1 = new CLQ_Rule__c(Name='Rule1',CLQ_Domain__c='Staff Files (FT)',CLQ_Rule_Effective_Date__c = (Date.today()).addDays(-10),CLQ_Rule_Expiration_Date__c = (Date.today()).adddays(10),CLQ_Description__c='test');
        ruleList.add(rule1);

        CLQ_Rule__c rule2 = new CLQ_Rule__c(Name='Rule2',CLQ_Domain__c='Staff Files (FT)',CLQ_Rule_Effective_Date__c = (Date.today()).addDays(-10),CLQ_Rule_Expiration_Date__c = (Date.today()).adddays(10),CLQ_Description__c='test');
        ruleList.add(rule2);

        insert ruleList;

        //Create Standard Findings
        list<CLQ_Standard_Findings__c> sfindingList = new list<CLQ_Standard_Findings__c>();
        CLQ_Standard_Findings__c sfinding = new CLQ_Standard_Findings__c(CLQ_Rules__c=rule1.id,Name='test',CLQ_Description__c='test',CLQ_Finding_Code__c='test',CLQ_Risk_Level__c='Serious');
        sfindingList.add(sfinding);
        CLQ_Standard_Findings__c sfinding2 = new CLQ_Standard_Findings__c(CLQ_Rules__c=rule2.id,Name='test2',CLQ_Description__c='test',CLQ_Finding_Code__c='test',CLQ_Risk_Level__c='Serious');
        sfindingList.add(sfinding2);
        insert sfindingList;

        //Create inspection  tool
        CLQ_Inspection_Tools__c inspectionTool = new CLQ_Inspection_Tools__c(name='Full',CLQ_Active__c = true,CLQ_Applicable_To__c='Child Care Center');
        insert inspectionTool;

        //Create tool rules

        CLQ_Tools_Rules__c toolRule = new CLQ_Tools_Rules__c(CLQ_Rules__c = rule1.id,CLQ_Inspection_Tools__c=inspectionTool.id);
        insert toolRule;

        CLQ_Rules_Inspected__c ruleInspected = new CLQ_Rules_Inspected__c(CLQ_Inspection_No__c=inspectionrecord.id,CLQ_Rule__c = rule1.id);
        insert ruleInspected ;

        CLQ_Findings__c finding = new CLQ_Findings__c(CLQ_Rules_Inspected__c=ruleInspected.id,CLQ_Standard_Finding__c=sfinding.id,CLQ_Description__c = 'test');
        insert finding;
        return inspectionrecord;
        }
	
}