DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Calculated_Max_Capacity__c</fullName>
        <description>The sum of square footage for all indoor approved primary space rooms marked as serving children Over 2 ½ divided by 35 +  the sum of the total Number of Children Allowed for all indoor approved primary space rooms where “Will children in this room be over or under 2 1/2?” is marked Under or Both</description>
        <label>Calculated Max Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Max_Capacity_Under_2_5_Years__c</fullName>
        <description>The sum of the total number of children allowed for all indoor approved primary space rooms where “Will children in this room be over or under 2 1/2?” is marked Under or Both. 

Value is determined based on room dimensions for rooms marked as serving children under 2 1/2 on the Classroom overlay(s) on the Room Information tab screen. 

System displays whole number only, rounded down</description>
        <label>Max Capacity Under 2 1/2 Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Max_Capacity_Under_2_Years__c</fullName>
        <label>Max Capacity Under 2 Years</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space__c.object
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <fields>
        <fullName>CLQ_Approved_Room_Space__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLQ_Calc_Nb_of_Child_Allowed_Indoor__c</fullName>
        <formula>ABS( CLQ_Square_Footage__c / 35)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Calculated Total Number of Children</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Room_Space_Type__c</fullName>
        <label>Room/Space Type</label>
        <picklist>
            <picklistValues>
                <fullName>Primary Space</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Additional Space</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Square_Footage__c</fullName>
        <formula>((CLQ_Width_Feet__c * 12 +  CLQ_Width_Inches__c ) * ( CLQ_Length_Feet__c * 12 +  CLQ_Length_Inches__c ))/144</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Square Footage</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Used_By_Under_or_Over_2__c</fullName>
        <label>Used by Under or Over 2</label>
        <picklist>
            <picklistValues>
                <fullName>Under</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Used_by_Under_or_Over_2_1_2__c</fullName>
        <label>Used by Under or Over 2 1/2</label>
        <picklist>
            <picklistValues>
                <fullName>Under</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_RoomOrGrptgrHandler.cls
public with sharing class CLQ_RoomOrGrptgrHandler {
	public static void updateformula(Map<Id,CLQ_Room_Space__c> NewRS, Map<Id,CLQ_Room_Space__c> OldRS) {
         set<id> RGSet = new set<id>();
		 Decimal foot = 0;
		 Decimal footage=0;
		 Decimal Nofc =0;
		 map<id,string> RTmap = new map <id,string>();
		 list<recordtype> RTlist = new list <recordtype>([select id,name from recordtype where sobjecttype = 'CLQ_Program__c']);
		 for(Recordtype R :RTlist){
		  RTmap.put(R.id,R.name);
		 }
		 for(CLQ_Room_Space__c RG : NewRS.values()){ 
		  RGset.add(RG.CLQ_Program__c);
		 }
		 list<CLQ_Program__c> updatelist = new list <CLQ_Program__c>();
		 list<CLQ_Program__c> Pgrlist = new list <CLQ_Program__c>([select id,name,recordtypeid from CLQ_Program__c where id IN: RGset]);
		 list<CLQ_Room_Space__c> RSListODE=new list<CLQ_Room_Space__c>([select id,name,recordtype.name,CLQ_Approved_Room_Space__c,CLQ_Square_Footage__c,CLQ_Room_Space_Type__c,CLQ_Used_by_Under_or_Over_2_1_2__c,CLQ_Used_By_Under_or_Over_2__c,CLQ_Program__c,CLQ_Program__r.recordtypeid from CLQ_Room_Space__c where recordtype.name =: 'Indoor Room/Space' and 
		                                  CLQ_Approved_Room_Space__c =: true and CLQ_Room_Space_Type__c=:'Primary Space' and (CLQ_Used_by_Under_or_Over_2_1_2__c =: 'Over' or CLQ_Used_By_Under_or_Over_2__c =:'Over')and CLQ_Program__c IN:RGset]);
		 list<CLQ_Room_Space__c> RSListbothODE=new list<CLQ_Room_Space__c>([select id,name,recordtype.name,CLQ_Calc_Nb_of_Child_Allowed_Indoor__c,CLQ_Approved_Room_Space__c,CLQ_Used_By_Under_or_Over_2__c,CLQ_Square_Footage__c,CLQ_Room_Space_Type__c,CLQ_Program__r.recordtypeid,CLQ_Used_by_Under_or_Over_2_1_2__c,CLQ_Program__c from CLQ_Room_Space__c where recordtype.name =: 'Indoor Room/Space' and 
		                                  CLQ_Approved_Room_Space__c =: true and CLQ_Room_Space_Type__c=:'Primary Space' and( (CLQ_Used_by_Under_or_Over_2_1_2__c =: 'Under' or CLQ_Used_by_Under_or_Over_2_1_2__c =: 'Both')or(CLQ_Used_By_Under_or_Over_2__c =: 'Under' or CLQ_Used_By_Under_or_Over_2__c =: 'Both'))and CLQ_Program__c IN:RGset]);
		 system.debug('Room Space ODE array size'+RSlistODE.size());
		 for(integer i=0;i<RSlistODE.size();i++){
		  
		  system.debug('RS count'+i);
		  foot = foot+RSlistODE[i].CLQ_Square_Footage__c;
		  system.debug('square footage'+foot);
		  } 
		 
		 for(integer i=0;i<RSlistbothODE.size();i++){
		 
		  NofC= Nofc+RSlistbothODE[i].CLQ_Calc_Nb_of_Child_Allowed_Indoor__c;
		  system.debug('both ODE child allowed indoor '+NofC);
		 }
		 
		 for(CLQ_Program__c pr:Pgrlist){
		 	if(RTmap.get(Pr.recordtypeid).contains('Type A')){
		 		system.debug('square footage type A'+foot);
		  		if(foot/35 > 12){
				   footage =12;
				   system.debug('footage for Type A'+footage);
		         }
		    }
		    else if(RTmap.get(Pr.recordtypeid).contains('Type B')){ 
		 	     system.debug('square footage type B'+footage);
		         if(foot/35 > 6){
		            footage =6;
		            system.debug('footage for Type B'+footage);
		          }
		    }
		    if(RSlistODE.size()>0){
		       pr.CLQ_Calculated_Max_Capacity__c=footage+NofC;
		    }
		   else{
		       pr.CLQ_Calculated_Max_Capacity__c=NofC;
		    }
		  
		   if(RTmap.get(Pr.recordtypeid).contains('FCC')){
		          pr.CLQ_Max_Capacity_Under_2_Years__c=NofC;
		          system.debug('CLQ_Max_Capacity_Under_2_Years__c'+pr.CLQ_Max_Capacity_Under_2_Years__c);
		 	}
		 	else if(RTmap.get(Pr.recordtypeid).contains('School')||RTmap.get(Pr.recordtypeid).contains('Child Care')){
		         pr.CLQ_Max_Capacity_Under_2_5_Years__c=NofC;
		     }
		 
		   
		 system.debug('CLQ_Calculated_Max_Capacity__c'+Pr.CLQ_Calculated_Max_Capacity__c);
		 updatelist.add(pr);
	   } //end program loop
		 
	   if(updatelist.size()>0){
		  update updatelist;
	   }
    }  
    
}