DevOCL/src/objects/CLQ_OCLQS_Configuration__c.object
<CustomObject>
    <description>This object will be used to set configuration needs for OCLQS per type of program.</description>
    <label>OCLQS Configuration</label>
    <nameField>
        <label>OCLQS Configuration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OCLQS Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Associated Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Licensing_Specialist__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Licensing Specialist</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_OCLQS_Configuration__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OCLQS Configuration</label>
        <referenceTo>CLQ_OCLQS_Configuration__c</referenceTo>
        <relationshipLabel>Programs</relationshipLabel>
        <relationshipName>Programs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <label>Street Address 1</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program_Transaction__c.object
<CustomObject>
    <description>This object is used to manage program applications</description>
    <fields>
        <fullName>CLQ_Associated_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Associated Organization</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Transaction_Assigned_To__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Program_Transactions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Room_Space__c.object
<CustomObject>
    <description>This is to document room/space information about a program.</description>
    <fields>
        <fullName>CLQ_Number_of_Children_Under_2__c</fullName>
        <label>Number of Children Under 2</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Transaction</label>
        <referenceTo>CLQ_Program_Transaction__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipName>Rooms_Spaces</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Street_Address_1__c</fullName>
        <formula>CLQ_Program__r.CLQ_Street_Address_1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Street Address 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CLQ_Used_By_Under_or_Over_2__c</fullName>
        <label>Used by Under or Over 2</label>
        <picklist>
            <picklistValues>
                <fullName>Under</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Over</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Both</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Room/Space Information</label>
    <nameField>
        <label>Room/Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms/Spaces</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_CreateTransactionInspectionExtnTest.cls
/* Name : CLQ_CreateTransactionInspectionExtnTest
* Description : This class/extension contains all test methods for CLQ_CreateTransactionInspectionExtn class. 
**/
@isTest
private class CLQ_CreateTransactionInspectionExtnTest {
	
	@isTest static void test_method_one() {
		//insert configuration record
        CLQ_OCLQS_Configuration__c configRecord = new CLQ_OCLQS_Configuration__c(Name = 'FCC - Type B Home');
        insert configRecord; 
                
        //Create account record
        Account accountrecord = new Account(Name='Test Account',CLQ_DIRN__c = '1234'); 
        insert accountrecord ;
                
        //Insert contact
        Contact contactrecord = new Contact(Firstname='test', lastName = 'Test',Accountid = accountrecord.id );
        insert contactrecord ;
                
        //Create a program record
        CLQ_Program__c programRecord = new CLQ_Program__c();
        programRecord.Name = 'Test';
        programRecord.CLQ_Associated_Organization__c = accountrecord.id;
        programRecord.CLQ_Street_Address_1__c = 'test';
        programRecord.recordTypeid = Schema.SObjectType.CLQ_Program__c.getRecordTypeInfosByName().get('FCC - Type B Home').getRecordTypeId();
        programRecord.CLQ_Licensing_Specialist__c = UserInfo.getUserid();
        insert programRecord ;
                
        //Create Room Space record
        CLQ_Room_Space__c roomSpace = new CLQ_Room_Space__c();
        roomSpace.CLQ_Program__c = programRecord.id;
        roomSpace.CLQ_Number_of_Children_Under_2__c = 2;
        roomSpace.CLQ_Used_By_Under_or_Over_2__c = 'Both';
        insert roomSpace;

        //Create Program Transaction record
        CLQ_Program_Transaction__c txRecord = new CLQ_Program_Transaction__c();
        txRecord.CLQ_Program__c = programRecord.id;
        txRecord.RecordTypeid = Schema.SObjectType.CLQ_Program_Transaction__c.getRecordTypeInfosByName().get('Amendment - Change of Capacity / Space').getRecordTypeId();
        txRecord.CLQ_Transaction_Assigned_To__c = UserInfo.getUserId();
        insert txRecord;

        Test.startTest();
        PageReference pageRef = Page.CLQ_CreateTransactionInspection;
        pageRef.getParameters().put('id',txRecord.id);

        //Set the current page
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController controller = new ApexPages.StandardController(txRecord);
        CLQ_CreateTransactionInspectionExtn extensionObject = new CLQ_CreateTransactionInspectionExtn(controller);
        extensionObject.programTransactionRecord = [SELECT id
                                                        ,CLQ_Program__r.Recordtypeid
                                                        ,CLQ_Transaction_Assigned_To__c
                                                        ,CLQ_Program__r.Id
                                                        ,CLQ_Program_Transaction__c.RecordTypeId
                                                FROM CLQ_Program_Transaction__c
                                                WHERE id = :txRecord.id];
        extensionObject.onLoad();
        extensionObject.onOK();
        Test.stopTest();
	}
	
}