DevOCL/src/objects/CLQ_Domain_Rule__c.object
<CustomObject>
    <description>Junction object between Rules and Domain</description>
    <fields>
        <fullName>CLQ_Applicable_To__c</fullName>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Alleged Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Care Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Home Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of State Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Age Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type A Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type B Home</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Rule_Effective_Date__c</fullName>
        <label>Rule Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CLQ_Rule_Expiration_Date__c</fullName>
        <label>Rule Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>Domain Rule</label>
    <nameField>
        <displayFormat>DR#-{000000}</displayFormat>
        <label>Domain Rule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Domain Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Inspection__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Inspection_Tool__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection Tool</label>
        <referenceTo>CLQ_Inspection_Tools__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program_Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program Transaction</label>
        <referenceTo>CLQ_Program_Transaction__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Inspections</relationshipLabel>
        <relationshipName>Inspections</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Reason_for_Inspection_Tool_Selection__c</fullName>
        <inlineHelpText>Provide reason if you are not selecting recommended tool</inlineHelpText>
        <label>Reason for Inspection Tool Selection</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CLQ_Recommended_Inspection_Tool__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recommended Inspection Tool</label>
        <referenceTo>CLQ_Inspection_Tools__c</referenceTo>
        <relationshipLabel>Inspections (Recommended Inspection Tool)</relationshipLabel>
        <relationshipName>Inspections1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Scope__c</fullName>
        <label>Scope</label>
        <picklist>
            <controllingField>CLQ_Inspection_Type__c</controllingField>
            <picklistValues>
                <fullName>Full</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Focused</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Use_Rules_Effective_On__c</fullName>
        <label>Use Rules Effective On</label>
        <type>Date</type>
    </fields>
    <label>Inspection</label>
    <nameField>
        <displayFormat>Inspection# {000000}</displayFormat>
        <label>Inspection No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inspections</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Inspection_Tools__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CLQ_Applicable_To__c</fullName>
        <label>Applicable To</label>
        <picklist>
            <picklistValues>
                <fullName>Alleged Ops</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Care Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Day Camp</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Home Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Out of State Registration</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pre School</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School Age Child Care</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCC - Type A Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCC - Type B Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type A Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Type B Home</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>CLQ_Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Inspection Tools</label>
    <nameField>
        <label>Inspection Tools Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inspection Tools</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program__c.object
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Program_Transaction__c.object
<CustomObject>
    <description>This object is used to manage program applications</description>
    <fields>
        <fullName>CLQ_Inspection__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>CLQ_Program__c</referenceTo>
        <relationshipLabel>Program Transactions</relationshipLabel>
        <relationshipName>Program_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Program Transaction</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Rules_Inspected__c.object
<CustomObject>
    <fields>
        <fullName>CLQ_Domain_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain Rule</label>
        <referenceTo>CLQ_Domain_Rule__c</referenceTo>
        <relationshipLabel>Rules Inspected</relationshipLabel>
        <relationshipName>Rules_Inspected</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Inspection_No__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection No</label>
        <referenceTo>CLQ_Inspection__c</referenceTo>
        <relationshipLabel>Rules Inspected</relationshipLabel>
        <relationshipName>Rules_Inspected</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rules Inspected</label>
    <nameField>
        <displayFormat>RI#-{000000}</displayFormat>
        <label>Rules Inspected No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rules Inspected</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/objects/CLQ_Tools_Rules__c.object
<CustomObject>
    <description>Junction object that manages the N:N relationship between the Visit Tool and Rules objects</description>
    <fields>
        <fullName>CLQ_Domain_Rule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Domain Rule</label>
        <referenceTo>CLQ_Domain_Rule__c</referenceTo>
        <relationshipLabel>Tools Rules</relationshipLabel>
        <relationshipName>Tools_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CLQ_Inspection_Tools__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Inspection Tools</label>
        <referenceTo>CLQ_Inspection_Tools__c</referenceTo>
        <relationshipLabel>Tools Rules</relationshipLabel>
        <relationshipName>Tools_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Tools Rules</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Tools Rules No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tools Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/CLQ_InspectionToolSelectionExtn.cls
public with sharing class CLQ_InspectionToolSelectionExtn {
	//Variables
	public list<String> fieldlist;
    public CLQ_Inspection__c inspectionRecord {get;set;}
    public list<innerInspectionToolClass> innerInspectionToolList{get;set;}
	//Constructor
	public CLQ_InspectionToolSelectionExtn(ApexPages.StandardController controller){
		inspectionRecord = new CLQ_Inspection__c();
		innerInspectionToolList = new list<innerInspectionToolClass>();
		fieldlist = new list<String>{'CLQ_Use_Rules_Effective_On__c','CLQ_Reason_for_Inspection_Tool_Selection__c','CLQ_Scope__c','CLQ_Program__c','CLQ_Program__r.RecordType.Name','CLQ_Program_Transaction__c','CLQ_Program_Transaction__r.CLQ_Program__r.RecordType.Name'};
		if(!Test.isRunningTest()){
            controller.addFields(fieldlist);
        }
        this.inspectionRecord = (CLQ_Inspection__c)controller.getRecord();	
	}

	//Method to get rules associated with the inspection tool
	//@param : inspection rule ID, validity Date
	//@return : list CLQ_Tools_Rules__c
	public list<CLQ_Tools_Rules__c> retriveToolRules(ID insepctionRule, Date validityDate){
		list<CLQ_Tools_Rules__c> toolRuleList = new list<CLQ_Tools_Rules__c>(); 
		toolRuleList = Database.query(CLQ_UtilityClass.createSOQLQuery('CLQ_Tools_Rules__c', ' CLQ_Inspection_Tools__c ='+'\''+insepctionRule+'\' AND CLQ_Domain_Rule__r.CLQ_Rule_Effective_Date__c<='+String.valueOf(validityDate)+' AND CLQ_Domain_Rule__r.CLQ_Rule_Expiration_Date__c>='+String.valueOf(validityDate)+'  AND CLQ_Domain_Rule__r.CLQ_Rule_Expiration_Date__c!= null', null));
		return 	toolRuleList;
	}

	//Method to get recommended inspection tool for given inspection
	//@param: inspection record
	//@return : list of inspection tools 
	public list<CLQ_Inspection_Tools__c> retriveInspectionTools(CLQ_Inspection__c inspectionRecord){
		list<CLQ_Inspection_Tools__c> inspectionToolList = new list<CLQ_Inspection_Tools__c>();
		inspectionToolList = [SELECT ID
								,CLQ_Applicable_To__c
								,CLQ_Description__c
								,CLQ_Active__c
								,Name
							FROM CLQ_Inspection_Tools__c
							];
							
		return inspectionToolList;
	}

	//Method to perform OnLoad logic
	//@param:
	//@return:
	public PageReference onLoad(){
		for(CLQ_Inspection_Tools__c inspectionToolrecord : retriveInspectionTools(inspectionRecord)){
			innerInspectionToolClass innerRecord = new innerInspectionToolClass(inspectionToolrecord);
			system.debug('====='+inspectionToolrecord.CLQ_Applicable_To__c)	;
			system.debug('====='+inspectionrecord.CLQ_Program__r.RecordType.Name);
			system.debug('====='+inspectionrecord.CLQ_Scope__c);
			if(inspectionToolrecord.CLQ_Applicable_To__c !=null 
				&& (inspectionToolrecord.CLQ_Applicable_To__c).contains(inspectionrecord.CLQ_Program__r.RecordType.Name)
				&& (inspectionToolrecord.Name).contains(inspectionrecord.CLQ_Scope__c)){
				innerRecord.isRecommended = true;
				innerRecord.isSelected = true;
				innerInspectionToolList.add(innerRecord);
			}else if(inspectionToolrecord.CLQ_Applicable_To__c !=null 
				&& (inspectionToolrecord.CLQ_Applicable_To__c).contains(inspectionrecord.CLQ_Program__r.RecordType.Name)
				&& !(inspectionToolrecord.Name).contains(inspectionrecord.CLQ_Scope__c)
				){
				innerInspectionToolList.add(innerRecord);
			}
			
		}
		return null;
	}

	//Wrapper class to show the table of Inspection tool 
	public class innerInspectionToolClass{
		public boolean isSelected{get;set;}
		public boolean isRecommended{get;set;}
		public CLQ_Inspection_Tools__c inspectionToolrecord {get; set;} 
		public String recommended{get;set;}

		public innerInspectionToolClass(CLQ_Inspection_Tools__c iTRecord){
			isSelected = false;
			isRecommended = false;
			recommended = 'Recommended';
			inspectionToolrecord = iTRecord;
		}
	}

	//Method to perform save method
	//@param:
	//@return :
	public PageReference onSave(){
		list<CLQ_Rules_Inspected__c> ruleInspectedList = new list<CLQ_Rules_Inspected__c>();
		for(innerInspectionToolClass innerRecord : innerInspectionToolList){
			if(innerRecord.isSelected == true){
				inspectionRecord.CLQ_Inspection_Tool__c = innerRecord.inspectionToolrecord.id;
			}
			if(innerRecord.isRecommended == true){
				inspectionRecord.CLQ_Recommended_Inspection_Tool__c = innerRecord.inspectionToolrecord.id;
			}
		}
		if((inspectionRecord.CLQ_Inspection_Tool__c != inspectionRecord.CLQ_Recommended_Inspection_Tool__c) 
			&& (inspectionRecord.CLQ_Reason_for_Inspection_Tool_Selection__c == '' 
			|| inspectionRecord.CLQ_Reason_for_Inspection_Tool_Selection__c == null)){
			ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please provide reason for selecting non-recommended tool'));
			return null;
			
		}else{
			update inspectionRecord;

			//Copy all rule associated with the selected inspection to inspection record
			for(CLQ_Tools_Rules__c toolRule : retriveToolRules(inspectionRecord.CLQ_Inspection_Tool__c,inspectionRecord.CLQ_Use_Rules_Effective_On__c)){
				ruleInspectedList.add(new CLQ_Rules_Inspected__c(CLQ_Inspection_No__c=inspectionRecord.id,CLQ_Domain_Rule__c =toolRule.CLQ_Domain_Rule__c));	
			}
			if(ruleInspectedList.size()>0){
				insert ruleInspectedList;
			}

			//Return to the inspection page
			return CLQ_UtilityClass.redirecttoPage('/'+inspectionRecord.Id);
			}
		
	}

	//Method to return to inspection detail page
	//@param:
	//@return:
	public PageReference onReturn(){
		//Return to the inspection page
		return CLQ_UtilityClass.redirecttoPage('/'+inspectionRecord.Id);
	}

}