DevOCL/src/objects/RuleSet__c.object
<CustomObject>
    <description>RuleSet Catalog and Rule object are in a 1 to many relationship. Contains Version, Rule Definition (JSON) and Activity Status</description>
    <fields>
        <fullName>Action_List__c</fullName>
        <label>Action List</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Catalog_ID__c</fullName>
        <label>Catalog ID</label>
        <referenceTo>RuleSet_Catalog__c</referenceTo>
        <relationshipLabel>RuleSet</relationshipLabel>
        <relationshipName>RuleSet</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Condition_List__c</fullName>
        <label>Condition List</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RuleSet_Name__c</fullName>
        <label>RuleSet Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rule_Definition__c</fullName>
        <label>Rule Definition</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compiled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compile Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RuleSet</label>
    <nameField>
        <displayFormat>RSID-{0000}</displayFormat>
        <label>RuleSet ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DevOCL/src/objects/RuleSet_Catalog__c.object
<CustomObject>
    <description>RuleSet Catalog defines basic information about each rule, including e.g. Name, Effective Start Date, Effective End Date, and Active Version</description>
    <fields>
        <fullName>Active_Class__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Active Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Active_Version__c</fullName>
        <defaultValue>&apos;Not Available&apos;</defaultValue>
        <label>Active Version</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_End_Date__c</fullName>
        <defaultValue>null</defaultValue>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Effective_Start_Date__c</fullName>
        <defaultValue>null</defaultValue>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>RuleSet Catalog</label>
    <nameField>
        <displayFormat>CID-{0000}</displayFormat>
        <label>Catalog ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RuleSet Catalog</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

DevOCL/src/classes/TestViewRuleSetController_V2.cls
@isTest
public class TestViewRuleSetController_V2 {

    public static testMethod void testViewRuleSetController(){
        PageReference ref = Page.ViewRuleSet_V2;
        Test.setCurrentPage(ref);
        
        RuleSet_Catalog__c catalog = new RuleSet_Catalog__c();
        catalog = new RuleSet_Catalog__c();
        catalog.Name__c = 'Test Catalog';
        catalog.Active_Class__c = 'Not Available';
        catalog.Active_Version__c = 'Not Available';
        insert catalog;
        
        RuleSet__c ruleset = new RuleSet__c();
        ruleset.RuleSet_Name__c = catalog.Name__c;
        ruleset.Catalog_ID__c = catalog.Id;
        ruleset.Status__c = 'Draft';
        ruleset.Effective_Start_Date__c = system.today();
        ruleset.Effective_End_Date__c = system.today().addyears(1);
        ruleset.Rule_Definition__c = '{"Rules":[{"Name":"Test Rule","ConditionMap":{"C1":true},"ActionOrder":{"A1":"1"},"ActionMap":{"A1":true}}],"Context":{"RuleVersion":"V-0129","RuleSetName":"Event Priority","RuleExecution":"All","returnType":"Void","RelatedObjectName":"Event_Request__c","InputObjects":[],"EffectiveStartDate":"2016-03-15","EffectiveEndDate":"2016-07-28"}}';
        ruleset.Condition_List__c = '[{"Value":"== 10","Status":null,"ParentFieldName":"None","Identifier":"C1","FieldName":"number_of_attendee__c","ConditionPretty":"number of attendee == 10"}]';
        ruleset.Action_List__c = '[{"Value":"somename","Type":"Add Record","resultObject":"Test_Action_Object__c","OrderNumber":null,"Identifier":"A1","Field":"name__c","ActionPretty":"somename"}]';
        insert ruleset;
        ApexPages.currentPage().getParameters().put('id', ruleset.Id);
        ViewRuleSetController_V2 rcontroller = new ViewRuleSetController_V2();
        
        PageReference pr = rcontroller.navigateToHome();
        PageReference expected = new PageReference('/apex/RulesHomePage_V2?id='+ruleset.Catalog_ID__c);
       // system.assertEquals(pr, expected);
        pr = rcontroller.navigateToConditionPanel();
        system.assertEquals(null, pr);
        pr = rcontroller.navigateToRulePanel();
        system.assertEquals(null, pr);
        pr = rcontroller.navigateToActionPanel();
        system.assertEquals(null, pr);
        pr = rcontroller.navigateToContextPage();
        system.assertEquals(null, pr);
        pr = rcontroller.navigateToConditionPage();
        system.assertEquals(null, pr);
        
        rcontroller.catalog = new List<RuleSet_Catalog__c>{catalog};
        ruleset.Rule_Definition__c = 'Not available';
        ruleset.Condition_List__c = 'Not available';
        ruleset.Action_List__c = 'Not available';
        update ruleset;
        rcontroller = new ViewRuleSetController_V2();
    }
}